package com.example.r_usecase.common

const val CHILD_ID = "id"
const val CHILD_BALANCE = "balance"
const val CHILD_FULLNAME = "fullname"
const val CHILD_CURRENCY_LIST = "currencyList"
const val CHILD_NAME = "name"
const val CHILD_RATE = "rate"
const val CHILD_EMAIL = "email"
const val CHILD_PHOTO_URL = "photoUrl"
const val CHILD_TYPE = "type"
const val CHILD_PHONE = "phone_number"
const val CHILD_DATE = "date"
const val CHILD_AMOUNT = "amount"
const val CHILD_TRANSACTION_CURRENCY= "transaction_currency"

const val USERS = "users"
const val HISTORY="history"
const val WALLETS="wallets"
const val QARZDORLAR="qarzdorlar"
const val HAQDORLAR="haqdorlar"
const val CURRENCIES="currencies"
const val TRANSACTIONS="transactions"
const val PERSONS="persons"
const val PERSON_CURRENCIES="personCurrencies"