package com.example.r_usecase.common

const val CHILD_ID = "id"
const val CHILD_FULLNAME = "fullname"
const val CHILD_EMAIL = "email"
const val CHILD_PHOTO_URL = "photoUrl"
const val CHILD_TYPE = "type"
const val CHILD_PHONE = "phone_number"
const val CHILD_DATE = "date"
const val CHILD_AMOUNT = "amount"
const val CHILD_TRANSACTION_CURRENCY= "transaction_currency"

const val EMAIL_USERS = "email_users"
const val GOOGLE_USERS="google_users"
const val HISTORY="history"
const val WALLETS="wallets"
const val QARZDORLAR="qarzdorlar"
const val HAQDORLAR="haqdorlar"
const val BALANCE="balance"
const val PEOPLES="peoples"